---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: projetasinhpa
spec:
  encryptedData:
    .dockerconfigjson: AgAeuIou1RrNZ8CkgzOaT1POvYRyByd0XjucYNCApIfHcfhCHRtwmkQ9zrUHnFeGN5pQ5yFGNdUCY4eVeFhGgWeSCUwOI68sDVgjYdbslv9DtnYx2Sdwu5pstpioubBcDYyAdjB9VtGVS7ngjFJ/rK8mOVnOSQQoSlCC2N6DWFtWqiiuqbndT956bW3C2syc4fmbn0+1tQiwWV8zYpd4cyox830fxkSTZqUNoFzgh5mHzqirjzssjkIKz6TEBWQd81kzgckJy6lvoiTsLMnsUzPpu2QoFdicxHzRlWdsGgwH/VuyuICfNgZxi5YebSwmFemYUUs365OmIKq9YWu015UyFMGI3dSrfHT7duBZ5nmQVgIxhOQtJkLG+0yNU7MM9qFaBPFAh37QxrIdRQJeGcavpbRR+Jb98UPTvdkYYTslP47pDcb2y7R3O+7IY4pYUqad1n2J/5j9nvcEbsuJpxfhZjon7PH4h9VCz03Ed4bIq01PuZh1f2xHWcNT+yIpeVbyaNEgLbNjALyeD91hlGSb2VhYoQ3HHfSQrxqbCJ/S8WVZPHKsW3PEU3E5K8pFWnV/02LMjlh65T5y7XxzjGP8ysLEsHVaNi0G7pj9PRGvCI/0CSie5PFv3JN59zYl81Av0zsgKHyJ2cPtx063sjtHfVtvzfy03iqmFrDOEZVK1ZInBVUKg43kOzJd/o+hgp0sb4vfspVHIc2EWr0Me4VRCNZuxZyCVDrzQCAuAVay4aZ8F9CgGXBff0VHkKlOMGZeZaSvSMAKrk/NN2p+dazwj5q1FQ0L0QMXAzrLThQTM8aVpQORwtwphtQbDLHF9n5un6erby9UnZDUVVoafX3fr6+zS8M138hXnGU8/pffv3jE6S9JkLJc2e4yCgZe2cSqNlEEklgAq4YU7Yk9jz9ZBZx0VRltzojfxgb2uMR1AmI7FLoPf+TDd8cvNJ9IyisXIE9sRH+uoHUqpGnJMNVNeQ1Il3n2H/jI0a93AwoeTrwA1FaB8pxprZn6qAQa23dJE5xvzPqlWvwAB6E=
  template:
    metadata:
      name: regcred
      namespace: projetasinhpa
    type: kubernetes.io/dockerconfigjson
